### PR TITLE
Continue passing medium importance tests throughout major version

### PR DESCRIPTION
**Pull request by jom**

### CODE REVIEW

**Comment by mdawaffe** [comment]
I actually don't know if this is the right behavior. What are the pros/cons? What should we be asking testers to do? If we implemented this test distributor, and an individual tester missed an `importance=5` test at some point, would we have blocked shipping? If we had shipped with that one tester missing that one test, does that mean other people completed the test, so this tester no longer needs to test it?

I don't have the answers :)

**Comment by mdawaffe** [comment]
Is this PR supposed to be off of master or off of store-full-environment-history?

**Comment by jom** [comment]
@mdawaffe Yup! Should have been. Created #3.

**Comment by mdawaffe** [comment]
Only somewhat related tot his PR: is "major release" in Jetpack synonymous with the semver definition? (I have no clue :)) That is, is Jetpack 4.5. a major release? Are the requirements for importance written and/or the notion of versioning in Jetpack written down anywhere?

**Pull request closed without merging**
